const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.Text,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.TextBox,
		C3.Plugins.Cryptography,
		C3.Plugins.BinaryData,
		C3.Plugins.Browser,
		C3.Plugins.Geolocation,
		C3.Plugins.Touch,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Cnds.OnParseSuccess,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.BinaryData.Acts.SetFromString,
		C3.Plugins.Cryptography.Acts.HashBinary,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Cryptography.Exps.Hash,
		C3.Plugins.Cryptography.Cnds.OnAnyHashFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.AJAX.Cnds.OnAnyComplete,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.AJAX.Cnds.OnAnyError,
		C3.Plugins.AJAX.Exps.LastStatusCode,
		C3.JavaScriptInEvents.事件表4_Event10,
		C3.JavaScriptInEvents.事件表4_Event18,
		C3.Plugins.Browser.Exps.QueryParam,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.JavaScriptInEvents.測試_Event2,
		C3.JavaScriptInEvents.測試_Event5,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.測試_Event7,
		C3.JavaScriptInEvents.測試_Event10,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{送出: 0},
	{AJAX: 0},
	{text1: 0},
	{JSON: 0},
	{文本2: 0},
	{陣列: 0},
	{dataInput: 0},
	{密碼學: 0},
	{二進制: 0},
	{瀏覽器: 0},
	{地理位置: 0},
	{觸控: 0},
	{讀取: 0},
	{改資料: 0},
	{搜尋: 0},
	{文本: 0},
	{文字: 0},
	{hashanswer: 0},
	{輸入: 0},
	{FM_Count: 0},
	{FM_ListJson: 0},
	{plykey: 0},
	{lineid: 0},
	{Level: 0}
];

self.InstanceType = {
	送出: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	text1: class extends self.ITextInstance {},
	JSON: class extends self.IJSONInstance {},
	文本2: class extends self.ITextInstance {},
	陣列: class extends self.IArrayInstance {},
	dataInput: class extends self.ITextInputInstance {},
	密碼學: class extends self.IInstance {},
	二進制: class extends self.IBinaryDataInstance {},
	瀏覽器: class extends self.IInstance {},
	地理位置: class extends self.IInstance {},
	觸控: class extends self.IInstance {},
	讀取: class extends self.IButtonInstance {},
	改資料: class extends self.IButtonInstance {},
	搜尋: class extends self.IButtonInstance {},
	文本: class extends self.ITextInstance {}
}